///|
pub let male_1_white_face : Json = {
  "angry": {
    "0": {
      "face": {
        "__h": 23,
        "__w": 25,
        "map": { "brow": [0, -13] },
        "origin": [12, 11],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [0, 131],
      },
    },
  },
  "bewildered": {
    "0": {
      "face": {
        "__h": 20,
        "__w": 26,
        "map": { "brow": [-1, -11] },
        "origin": [13, 10],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [132, 21],
      },
    },
  },
  "blaze": {
    "0": {
      "delay": 110,
      "face": {
        "__h": 21,
        "__w": 30,
        "map": { "brow": [0, -10] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [102, 23],
      },
    },
    "1": {
      "delay": 110,
      "face": {
        "__h": 23,
        "__w": 30,
        "map": { "brow": [0, -8] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [102, 0],
      },
    },
  },
  "blink": {
    "0": {
      "delay": 60,
      "face": {
        "__h": 16,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [76, 68],
      },
    },
    "1": {
      "delay": 60,
      "face": {
        "__h": 16,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [81, 93],
      },
    },
    "2": {
      "delay": 60,
      "face": {
        "__h": 16,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [0, 115],
      },
    },
  },
  "bowing": {
    "0": {
      "delay": 110,
      "face": {
        "__h": 20,
        "__w": 36,
        "map": { "brow": [11, -11] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [40, 68],
      },
    },
    "1": {
      "delay": 110,
      "face": {
        "__h": 20,
        "__w": 37,
        "map": { "brow": [12, -11] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [42, 48],
      },
    },
  },
  "cheers": {
    "0": {
      "face": {
        "__h": 21,
        "__w": 26,
        "map": { "brow": [-1, -11] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [132, 0],
      },
    },
  },
  "chu": {
    "0": {
      "face": {
        "__h": 16,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [26, 115],
      },
    },
  },
  "cry": {
    "0": {
      "face": {
        "__h": 12,
        "__w": 26,
        "map": { "brow": [-1, -10] },
        "origin": [13, 6],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [104, 115],
      },
    },
  },
  "dam": {
    "0": {
      "delay": 240,
      "face": {
        "__h": 22,
        "__w": 24,
        "map": { "brow": [0, 0] },
        "origin": [11, -2],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [158, 23],
      },
    },
    "1": {
      "delay": 240,
      "face": {
        "__h": 23,
        "__w": 24,
        "map": { "brow": [0, 0] },
        "origin": [11, -1],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [158, 0],
      },
    },
  },
  "default": {
    "face": {
      "__h": 16,
      "__w": 26,
      "map": { "brow": [-1, -12] },
      "origin": [13, 8],
      "z": "face",
      "__i": "/assets/character/body/male_1_white_face.png",
      "__off": [132, 92],
    },
  },
  "despair": {
    "0": {
      "delay": 150,
      "face": {
        "__h": 20,
        "__w": 42,
        "map": { "brow": [14, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [0, 48],
      },
    },
    "1": {
      "delay": 150,
      "face": {
        "__h": 20,
        "__w": 44,
        "map": { "brow": [16, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [56, 26],
      },
    },
  },
  "glitter": {
    "0": {
      "delay": 150,
      "face": {
        "__h": 19,
        "__w": 27,
        "map": { "brow": [0, -9] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [27, 93],
      },
    },
    "1": {
      "delay": 150,
      "face": {
        "__h": 19,
        "__w": 27,
        "map": { "brow": [0, -9] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [54, 93],
      },
    },
  },
  "hit": {
    "0": {
      "face": {
        "__h": 15,
        "__w": 25,
        "map": { "brow": [0, -11] },
        "origin": [12, 7],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [107, 93],
      },
    },
  },
  "hot": {
    "0": {
      "delay": 110,
      "face": {
        "__h": 25,
        "__w": 40,
        "map": { "brow": [16, -10] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [0, 68],
      },
    },
    "1": {
      "delay": 110,
      "face": {
        "__h": 26,
        "__w": 46,
        "map": { "brow": [21, -9] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [56, 0],
      },
    },
  },
  "hum": {
    "0": {
      "delay": 110,
      "face": {
        "__h": 21,
        "__w": 25,
        "map": { "brow": [-2, -9] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [25, 131],
      },
    },
    "1": {
      "delay": 110,
      "face": {
        "__h": 21,
        "__w": 25,
        "map": { "brow": [-2, -9] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [50, 131],
      },
    },
  },
  "info": { "cash": 1, "islot": "Fc", "vslot": "Fc" },
  "love": {
    "0": {
      "delay": 150,
      "face": {
        "__h": 22,
        "__w": 27,
        "map": { "brow": [0, -9] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [102, 63],
      },
    },
    "1": {
      "delay": 150,
      "face": {
        "__h": 22,
        "__w": 27,
        "map": { "brow": [0, -9] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [0, 93],
      },
    },
  },
  "oops": {
    "0": {
      "face": {
        "__h": 15,
        "__w": 25,
        "map": { "brow": [0, -11] },
        "origin": [12, 7],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [75, 131],
      },
    },
    "delay": 1640,
  },
  "pain": {
    "0": {
      "face": {
        "__h": 19,
        "__w": 30,
        "map": { "brow": [1, -8] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [102, 44],
      },
    },
  },
  "shine": {
    "0": {
      "face": {
        "__h": 16,
        "__w": 26,
        "map": { "brow": [0, -8] },
        "origin": [13, 6],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [78, 115],
      },
    },
  },
  "smile": {
    "0": {
      "face": {
        "__h": 17,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [132, 41],
      },
    },
  },
  "stunned": {
    "0": {
      "face": {
        "__h": 17,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [132, 75],
      },
    },
  },
  "troubled": {
    "0": {
      "face": {
        "__h": 17,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [132, 58],
      },
    },
  },
  "vomit": {
    "0": {
      "delay": 120,
      "face": {
        "__h": 48,
        "__w": 28,
        "map": { "brow": [0, -28] },
        "origin": [14, 24],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [0, 0],
      },
    },
    "1": {
      "delay": 120,
      "face": {
        "__h": 48,
        "__w": 28,
        "map": { "brow": [0, -28] },
        "origin": [14, 24],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [28, 0],
      },
    },
  },
  "wink": {
    "0": {
      "face": {
        "__h": 16,
        "__w": 26,
        "map": { "brow": [-1, -12] },
        "origin": [13, 8],
        "z": "face",
        "__i": "/assets/character/body/male_1_white_face.png",
        "__off": [52, 115],
      },
    },
  },
}
