///|
let install_texts : Json = {
  "3010000": {
    "desc": "Catch your breath and relax by sitting on this chair to recover 50 HP every 10 seconds.\\n#cCannot be traded or dropped.#",
    "name": "The Relaxer",
  },
  "3010001": {
    "desc": "A specially-made sky-blue wooden chair that's only available in Lith Harbor. Recover 35 HP every 10 seconds.",
    "name": "Sky-blue Wooden Chair",
  },
  "3010002": {
    "desc": "A comfortable, plush green chair, complete with arm-rests. Recovers 50 HP every 10 seconds.",
    "name": "Green Chair",
  },
  "3010003": {
    "desc": "A comfortable, plush red chair, complete with arm-rests.. Recovers 50 HP every 10 seconds.",
    "name": "Red Chair",
  },
  "3010004": {
    "desc": "Catch your breath and relax by sitting on this chair to recover 50 HP every 10 seconds. Perfect for a quick break from training.",
    "name": "The Yellow Relaxer",
  },
  "3010005": {
    "desc": "Catch your breath and relax by sitting on this chair to recover 50 HP every 10 seconds.  Perfect for a quick break from training.",
    "name": "The Red Relaxer",
  },
  "3010006": {
    "desc": "A comfortable, plush yellow chair, complete with arm-rests. Recovers 50 HP every 10 seconds.",
    "name": "Yellow Chair",
  },
  "3010007": {
    "desc": "An adorable pink cushion that resembles a seal.  Recovers HP 60 every 10 seconds.",
    "name": "Pink Seal Cushion",
  },
  "3010008": {
    "desc": "An adorable blue cushion that resembles a seal.  Recovers HP 60 every 10 seconds.",
    "name": "Blue Seal Cushion",
  },
  "3010009": {
    "desc": "Rumored to be crafted in Amoria, this special chair is also known as the Love Seat. Recover 20 HP and 20 MP every 10 seconds.",
    "name": "Red Round Chair",
  },
  "3010010": {
    "desc": "An adorable white cushion that resembles a seal.  Recovers HP 50 every 10 seconds.",
    "name": "White Seal Cushion",
  },
  "3010011": {
    "desc": "A chair crafted by Jacob. Recovers 75 HP every 10 seconds.\\n#cCannot be traded or dropped.#",
    "name": "Amorian Relaxer",
  },
  "3010012": {
    "desc": "A powerful chair used often on the battlefield. Recovers 60 HP every 10 seconds.\\n#cCannot be traded or dropped.#",
    "name": "Warrior Throne",
  },
  "3010013": {
    "desc": "A chair straight from the relaxation experts in Florina Beach. Recover 20 HP every 10 seconds.",
    "name": "Beach Chair",
  },
  "3010014": {
    "desc": "A light, stylish chair that seems to be sent from the heavens. Recover 30 HP and 30 MP every 10 seconds.",
    "name": "Moon Star Chair",
  },
  "3010015": {
    "desc": "A chair with magical properties crafted in Ellinia. Restores 35 MP per 10 Seconds while sitting.",
    "name": "The Red Relaxer",
  },
  "3010016": {
    "desc": "An adorable grey cushion that resembles a seal.  Recovers HP 60 every 10 seconds.",
    "name": "Grey Seal Cushion",
  },
  "3010017": {
    "desc": "An adorable gold cushion that resembles a seal.  Recovers MP 60 every 10 seconds.",
    "name": "Gold Seal Cushion",
  },
  "3010018": {
    "desc": "A beach chair placed in the shades under the palm tree at Ariant. Sit on it to recover HP 40 and MP 20 every 10 seconds.",
    "name": "Palm Tree Beach Chair",
  },
  "3010019": {
    "desc": "A specially-made chair that's only available in Mushroom Shrine. Recover 60 MP every 10 seconds.",
    "name": "Kadomatsu",
  },
  "3010025": {
    "desc": "A white chair commemorating the 4th anniversary of MapleStory. Sit on it to recover HP 35 and MP 10 every 10 seconds.",
    "name": "Under the Maple Tree...",
  },
  "3010040": {
    "desc": "A chair hand-crafted by Stirgeman for aspiring superheroes! Recovers 50 HP and 50 MP every 10 seconds.",
    "name": "The Stirge Seat",
  },
  "3010041": {
    "desc": "A chair crafted within the Phantom Forest, complete with...ornaments...from unlucky travelers. Recovers 50 HP and 50 MP every 10 seconds.",
    "name": "Skull Throne",
  },
  "3010043": {
    "desc": "When you sit on the Halloween Broomstick Chair, 50 MP is restored every 10 seconds",
    "name": "Halloween Broomstick Chair",
  },
  "3010044": {
    "desc": "A chair with a big umbrella. Recovers 30 HP and 30 MP every 10 seconds.",
    "name": "Winter Red Chair ",
  },
  "3010045": {
    "desc": "A chair made out of Ice Queen's ice pieces. Sit on it to recover HP 40 and MP 30 per 10 seconds.",
    "name": "Ice Chair",
  },
  "3010046": {
    "desc": "Inferno will comfort your body. Recovers 60 HP every 10 seconds.",
    "name": "Dragon Chair(Inferno)",
  },
  "3010047": {
    "desc": "Abyss will comfort your mind. Recovers 60 MP every 10 seconds.",
    "name": "Dragon Chair(Abyss)",
  },
  "3010057": {
    "desc": "You will recover 50 HP every 10 seconds. You will experience the might of a conqueror after recovery.",
    "name": "BloodyRose",
  },
  "3010058": {
    "desc": "You will recover 50 HP every 10 seconds. Perhaps, as you recline, you will find the answer to many of life's questions.",
    "name": "WorldEnd",
  },
  "3010060": {
    "desc": "A chair makes you feel like you're sitting in the lap of luxury. Also recovers 50 HP every 10 seconds.",
    "name": "Noblesse Chair",
  },
  "3010061": {
    "desc": "A white chair created to celebrate Maple Story's 6th Anniversary. Sit on it to restore 35 HP and 10 MP every 10 seconds.",
    "name": "Underneath the Maple Tree…",
  },
  "3010062": {
    "desc": "A chair that restores HP every 10 seconds when used. It's very strong since it was made from bamboo grown on Rien.",
    "name": "Bamboo Chair ",
  },
  "3010063": {
    "desc": "A pretty cushion shaped like a moon. Recovers 60 HP every 10 seconds.",
    "name": "Moon and Star Cushion",
  },
  "3010064": {
    "desc": "60 HP is restored every 10 seconds if you lean back on this cute Male Desert Rabbit Cushion.",
    "name": "Male Desert Rabbit Cushion  ",
  },
  "3010065": {
    "desc": "A pink beach chair that makes you want to go to the beach. Restores 60 HP every 10 seconds.",
    "name": "Pink Beach Parasol",
  },
  "3010066": {
    "desc": "A luxurious velvet sofa dyed with a beautiful shade of navy. Restores 60 HP every 10 seconds.",
    "name": "Navy Velvet Sofa  ",
  },
  "3010067": {
    "desc": "A designer chair that glows with a passionate red. Restores 60 HP every 10 seconds.",
    "name": "Red Designer Chair  ",
  },
  "3010069": {
    "desc": "Perch yourself on the hand of this powerful yellow robot to recover 50 HP and 30 MP every 10 seconds.",
    "name": "Yellow Robot Chair",
  },
  "3010071": {
    "desc": "When you rest on the Shinsoo, 50 HP and 50 MP are restored every 10 seconds",
    "name": "Mini Shinsoo Chair",
  },
  "3010072": {
    "desc": "The chair in which the chiefs of the Miwok tribe sat. If you sit in this chair, you can receive the strength of the Miwok ancestors and recover 65MP in 10 seconds.",
    "name": "Miwok Chief's Chair",
  },
  "3010073": {
    "desc": "A cushion that resembles Pink Bean, the underling of the Black Mage. Leaning against the cushion and resting will recover 50 HP and 30 MP every 10 seconds. ",
    "name": "Giant Pink Bean Cushion",
  },
  "3010080": {
    "desc": "There is a swing on the Persimmon Tree with ripe persimmons.",
    "name": "Swing on the Persimmon Tree",
  },
  "3010081": {
    "desc": "방석에 앉으면 빨간 상모를 쓴 귀여운 월묘의 재주를 볼 수 있다.",
    "name": "홍상모 월묘 방석",
  },
  "3010082": {
    "desc": "방석에 앉으면 파란 상모를 쓴 귀여운 월묘의 재주를 볼 수 있다.",
    "name": "청상모 월묘 방석",
  },
  "3010083": {
    "desc": "방석에 앉으면 부채를 들고 줄타기를 하는 월묘의 재주를 볼 수 있다.",
    "name": "부채춤 월묘 방석",
  },
  "3010084": {
    "desc": "방석에 앉으면 혼신의 힘을 다해 연주하는 월묘를 볼 수 있다.",
    "name": "태평소 월묘 방석",
  },
  "3010085": {
    "desc": "An eerie looking chair that resembles Olivia. Recovers 40 HP and 35 MP every 10 seconds",
    "name": "Olivia's Chair",
  },
  "3010092": {
    "desc": "Hold onto the Broomstick so you don't fall off.",
    "name": "Witch's Broomstick",
  },
  "3010098": {
    "desc": "A new chair to recline and relax in throughout the Thanksgiving holiday.\\nRecovers 60 HP and 30 MP every 10 seconds.",
    "name": "TV Recliner",
  },
  "3010099": {
    "desc": "Cuddling with the Polar Bear for some cozy, comfy rest will recover 50 HP and 50 MP every 10 seconds.",
    "name": "Cuddly Polar Bear",
  },
  "3010101": {
    "desc": "A huge X-mas Gift Box big enough to fit a grownup. It has a message that reads, \"I am here for you.\" Sitting in it will recover 50 HP and MP every 10 seconds.",
    "name": "Christmas Gift Box",
  },
  "3010106": {
    "desc": "Snuggle up with Aran's loyal mount, Ryko, to recover 50 HP and MP every 10 seconds.",
    "name": "Ryko Chair",
  },
  "3010111": {
    "desc": "Lean back on this imposing Tiger Skin Chair to restore 50 HP and 30 MP every 10 seconds.",
    "name": "Tiger Skin Chair",
  },
  "3010116": {
    "desc": "A new chair that makes you feel like a Rock Star.\\nRecovers 60 HP and 30 MP every 10 seconds.",
    "name": "The Spirit of Rock Chair",
  },
  "3011000": {
    "desc": "The perfect chair for fishing.",
    "name": "Fishing Chair",
  },
  "3012005": {
    "desc": "A comfortable, stylish seat that only forms when true love exists between two people.  Recovers 45 HP, 45 MP every 10 seconds.",
    "name": "Amorian Loveseat",
  },
  "3012010": {
    "desc": "Sink yourself into this heavenly cake chair next to someone else who owns it as well, and watch it create a scrumptious effect! Mmm, this chair is so delicious you'll recover 50 HP every 10 seconds.",
    "name": "Half-Heart Chocolate Cake Chair",
  },
  "3012011": {
    "desc": "Yummy! Use this chair next to someone else who's also using it, and a mouth-watering chocolate fondue appears. Smack your lips and dream about treats as you recover 50 HP every 10 seconds. ",
    "name": "Chocolate Fondue Chair",
  },
  "3990000": { "desc": "A red #1 to decorate the tree.", "name": "Red No. 1" },
  "3990001": { "desc": "A red #2 to decorate the tree.", "name": "Red No. 2" },
  "3990002": { "desc": "A red #3 to decorate the tree.", "name": "Red No. 3" },
  "3990003": { "desc": "A red #4 to decorate the tree.", "name": "Red No. 4" },
  "3990004": { "desc": "A red #5 to decorate the tree.", "name": "Red No. 5" },
  "3990005": { "desc": "A red #6 to decorate the tree.", "name": "Red No. 6" },
  "3990006": { "desc": "A red #7 to decorate the tree.", "name": "Red No. 7" },
  "3990007": { "desc": "A red #8 to decorate the tree.", "name": "Red No. 8" },
  "3990008": { "desc": "A red #9 to decorate the tree.", "name": "Red No. 9" },
  "3990009": { "desc": "A red #0 to decorate the tree.", "name": "Red No. 0" },
  "3990010": {
    "desc": "A green #1 to decorate the tree.",
    "name": "Green No. 1",
  },
  "3990011": {
    "desc": "A green #2 to decorate the tree.",
    "name": "Green No. 2",
  },
  "3990012": {
    "desc": "A green #3 to decorate the tree.",
    "name": "Green No. 3",
  },
  "3990013": {
    "desc": "A green #4 to decorate the tree.",
    "name": "Green No. 4",
  },
  "3990014": {
    "desc": "A green #5 to decorate the tree.",
    "name": "Green No. 5",
  },
  "3990015": {
    "desc": "A green #6 to decorate the tree.",
    "name": "Green No. 6",
  },
  "3990016": {
    "desc": "A green #7 to decorate the tree.",
    "name": "Green No. 7",
  },
  "3990017": {
    "desc": "A green #8 to decorate the tree.",
    "name": "Green No. 8",
  },
  "3990018": {
    "desc": "A green #9 to decorate the tree.",
    "name": "Green No. 9",
  },
  "3990019": {
    "desc": "A green #0 to decorate the tree.",
    "name": "Green No. 0",
  },
  "3990020": {
    "desc": "A red \" + \" to decorate the tree.",
    "name": "Red \" + \"",
  },
  "3990021": {
    "desc": "A red \" - \" to decorate the tree.",
    "name": "Red \" - \"",
  },
  "3990022": {
    "desc": "A green \" + \" to decorate the tree.",
    "name": "Green \" + \"",
  },
  "3990023": {
    "desc": "A green \" - \" to decorate the tree.",
    "name": "Green \" - \"",
  },
  "3991000": {
    "desc": "A red \"A\" to decorate the tree.",
    "name": "Red \"A\"",
  },
  "3991001": {
    "desc": "A red \"B\" to decorate the tree.",
    "name": "Red \"B\"",
  },
  "3991002": {
    "desc": "A red \"C\" to decorate the tree.",
    "name": "Red \"C\"",
  },
  "3991003": {
    "desc": "A red \"D\" to decorate the tree.",
    "name": "Red \"D\"",
  },
  "3991004": {
    "desc": "A red \"E\" to decorate the tree.",
    "name": "Red \"E\"",
  },
  "3991005": {
    "desc": "A red \"F\" to decorate the tree.",
    "name": "Red \"F\"",
  },
  "3991006": {
    "desc": "A red \"G\" to decorate the tree.",
    "name": "Red \"G\"",
  },
  "3991007": {
    "desc": "A red \"H\" to decorate the tree.",
    "name": "Red \"H\"",
  },
  "3991008": {
    "desc": "A red \"I\" to decorate the tree.",
    "name": "Red \"I\"",
  },
  "3991009": {
    "desc": "A red \"J\" to decorate the tree.",
    "name": "Red \"J\"",
  },
  "3991010": {
    "desc": "A red \"K\" to decorate the tree.",
    "name": "Red \"K\"",
  },
  "3991011": {
    "desc": "A red \"L\" to decorate the tree.",
    "name": "Red \"L\"",
  },
  "3991012": {
    "desc": "A red \"M\" to decorate the tree.",
    "name": "Red \"M\"",
  },
  "3991013": {
    "desc": "A red \"N\" to decorate the tree.",
    "name": "Red \"N\"",
  },
  "3991014": {
    "desc": "A red \"O\" to decorate the tree.",
    "name": "Red \"O\"",
  },
  "3991015": {
    "desc": "A red \"P\" to decorate the tree.",
    "name": "Red \"P\"",
  },
  "3991016": {
    "desc": "A red \"Q\" to decorate the tree.",
    "name": "Red \"Q\"",
  },
  "3991017": {
    "desc": "A red \"R\" to decorate the tree.",
    "name": "Red \"R\"",
  },
  "3991018": {
    "desc": "A red \"S\" to decorate the tree.",
    "name": "Red \"S\"",
  },
  "3991019": {
    "desc": "A red \"T\" to decorate the tree.",
    "name": "Red \"T\"",
  },
  "3991020": {
    "desc": "A red \"U\" to decorate the tree.",
    "name": "Red \"U\"",
  },
  "3991021": {
    "desc": "A red \"V\" to decorate the tree.",
    "name": "Red \"V\"",
  },
  "3991022": {
    "desc": "A red \"W\" to decorate the tree.",
    "name": "Red \"W\"",
  },
  "3991023": {
    "desc": "A red \"X\" to decorate the tree.",
    "name": "Red \"X\"",
  },
  "3991024": {
    "desc": "A red \"Y\" to decorate the tree.",
    "name": "Red \"Y\"",
  },
  "3991025": {
    "desc": "A red \"Z\" to decorate the tree.",
    "name": "Red \"Z\"",
  },
  "3991026": {
    "desc": "A green \"A\" to decorate the tree.",
    "name": "Green \"A\"",
  },
  "3991027": {
    "desc": "A green \"B\" to decorate the tree.",
    "name": "Green \"B\"",
  },
  "3991028": {
    "desc": "A green \"C\" to decorate the tree.",
    "name": "Green \"C\"",
  },
  "3991029": {
    "desc": "A green \"D\" to decorate the tree.",
    "name": "Green \"D\"",
  },
  "3991030": {
    "desc": "A green \"E\" to decorate the tree.",
    "name": "Green \"E\"",
  },
  "3991031": {
    "desc": "A green \"F\" to decorate the tree.",
    "name": "Green \"F\"",
  },
  "3991032": {
    "desc": "A green \"G\" to decorate the tree.",
    "name": "Green \"G\"",
  },
  "3991033": {
    "desc": "A green \"H\" to decorate the tree.",
    "name": "Green \"H\"",
  },
  "3991034": {
    "desc": "A green \"I\" to decorate the tree.",
    "name": "Green \"I\"",
  },
  "3991035": {
    "desc": "A green \"J\" to decorate the tree.",
    "name": "Green \"J\"",
  },
  "3991036": {
    "desc": "A green \"K\" to decorate the tree.",
    "name": "Green \"K\"",
  },
  "3991037": {
    "desc": "A green \"L\" to decorate the tree.",
    "name": "Green \"L\"",
  },
  "3991038": {
    "desc": "A green \"M\" to decorate the tree.",
    "name": "Green \"M\"",
  },
  "3991039": {
    "desc": "A green \"N\" to decorate the tree.",
    "name": "Green \"N\"",
  },
  "3991040": {
    "desc": "A green \"O\" to decorate the tree.",
    "name": "Green \"O\"",
  },
  "3991041": {
    "desc": "A green \"P\" to decorate the tree.",
    "name": "Green \"P\"",
  },
  "3991042": {
    "desc": "A green \"Q\" to decorate the tree.",
    "name": "Green \"Q\"",
  },
  "3991043": {
    "desc": "A green \"R\" to decorate the tree.",
    "name": "Green \"R\"",
  },
  "3991044": {
    "desc": "A green \"S\" to decorate the tree.",
    "name": "Green \"S\"",
  },
  "3991045": {
    "desc": "A green \"T\" to decorate the tree.",
    "name": "Green \"T\"",
  },
  "3991046": {
    "desc": "A green \"U\" to decorate the tree.",
    "name": "Green \"U\"",
  },
  "3991047": {
    "desc": "A green \"V\" to decorate the tree.",
    "name": "Green \"V\"",
  },
  "3991048": {
    "desc": "A green \"W\" to decorate the tree.",
    "name": "Green \"W\"",
  },
  "3991049": {
    "desc": "A green \"X\" to decorate the tree.",
    "name": "Green \"X\"",
  },
  "3991050": {
    "desc": "A green \"Y\" to decorate the tree.",
    "name": "Green \"Y\"",
  },
  "3991051": {
    "desc": "A green \"Z\" to decorate the tree.",
    "name": "Green \"Z\"",
  },
  "3992000": {
    "desc": "A santa ornament for the tree.",
    "name": "Santa Ornament",
  },
  "3992001": {
    "desc": "A Rudolph ornament for the tree.",
    "name": "Rudolph Ornament",
  },
  "3992002": {
    "desc": "A mushroom ornament for the tree.",
    "name": "Mushroom Ornament",
  },
  "3992003": { "desc": "A pig ornament for the tree.", "name": "Pig Ornament" },
  "3992004": {
    "desc": "A slime ornament for the tree.",
    "name": "Slime Ornament",
  },
  "3992005": {
    "desc": "A red gift-box ornament for the tree.",
    "name": "Red Gift-Box Ornament",
  },
  "3992006": {
    "desc": "A blue gift-box ornament for the tree.",
    "name": "Blue Gift-Box Ornament",
  },
  "3992007": {
    "desc": "A yellow gift-box ornament for the tree.",
    "name": "Yellow Gift-Box Ornament",
  },
  "3992008": {
    "desc": "A red star miniature bulb for the tree.",
    "name": "Red Star Miniature Bulb",
  },
  "3992009": {
    "desc": "A blue star miniature bulb for the tree.",
    "name": "Blue Star Miniature Bulb",
  },
  "3992010": {
    "desc": "A green star miniature bulb for the tree.",
    "name": "Green Star Miniature Bulb",
  },
  "3992011": {
    "desc": "A pink star miniature bulb for the tree.",
    "name": "Pink Star Miniature Bulb",
  },
  "3992012": {
    "desc": "An orange star miniature bulb for the tree.",
    "name": "Orange Star Miniature Bulb",
  },
  "3992013": {
    "desc": "A red miniature bulb for the tree.",
    "name": "Red Miniature Bulb",
  },
  "3992014": {
    "desc": "A blue miniature bulb for the tree.",
    "name": "Blue Miniature Bulb",
  },
  "3992015": {
    "desc": "A yellow miniature bulb for the tree.",
    "name": "Yellow Miniature Bulb",
  },
  "3992016": {
    "desc": "A green miniature bulb for the tree.",
    "name": "Green Miniature Bulb",
  },
  "3992017": {
    "desc": "A red ball ornament for the tree.",
    "name": "Red Ball Ornament",
  },
  "3992018": {
    "desc": "A blue ball ornament for the tree.",
    "name": "Blue Ball Ornament",
  },
  "3992019": {
    "desc": "A yellow ball ornament for the tree.",
    "name": "Yellow Ball Ornament",
  },
  "3992020": { "desc": "A red sock for the tree.", "name": "Red Sock" },
  "3992021": {
    "desc": "The gingerbread man for the tree.",
    "name": "The gingerbread man",
  },
  "3992022": {
    "desc": "The gingerbread lady for the tree.",
    "name": "The gingerbread woman",
  },
  "3992023": { "desc": "A candy cane for the tree.", "name": "Candy Cane" },
  "3992024": {
    "desc": "A circular ornament for the tree.",
    "name": "Circular Tree Ornament",
  },
  "3992025": {
    "desc": "A king-sized star for the tree.",
    "name": "King-sized Star",
  },
  "3992026": {
    "desc": "A christmas wreath for the tree.",
    "name": "Christmas wreath",
  },
  "3992027": { "desc": "A red candle for the tree.", "name": "Red Candle" },
  "3992028": { "desc": "A blue candle for the tree.", "name": "Blue Candle" },
  "3992029": {
    "desc": "A yellow candle for the tree.",
    "name": "Yellow Candle",
  },
  "3992030": {
    "desc": "Red candy canes for the tree.",
    "name": "Red Candy Canes",
  },
  "3992031": {
    "desc": "Blue candy canes for the tree.",
    "name": "Blue Candy Canes",
  },
  "3992032": {
    "desc": "Yellow candy canes for the tree.",
    "name": "Yellow Candy Canes",
  },
  "3992033": {
    "desc": "Red fruit leaves for the tree.",
    "name": "Red Fruit Leaves",
  },
  "3992034": {
    "desc": "Yellow fruit leaves for the tree.",
    "name": "Yellow Fruit Leaves",
  },
  "3992035": {
    "desc": "A red-ribboned giftbox for the tree.",
    "name": "Red-Ribboned Giftbox",
  },
  "3992036": {
    "desc": "A blue-ribboned giftbox for the tree.",
    "name": "Blue-Ribboned Giftbox",
  },
  "3992037": {
    "desc": "A yellow-ribboned giftbox for the tree.",
    "name": "Yellow-Ribboned Giftbox",
  },
  "3992038": {
    "desc": "A Rudolph Santa Boots for the tree.",
    "name": "Ruldolph Santa Boots",
  },
  "3992039": {
    "desc": "A small figurine embedded with a gem that emanates heroism.  This item allows you to activate and use the Heroic Statues in the Valley of Heroes.",
    "name": "Marker of Heroism",
  },
  "3992040": {
    "desc": "This map marks the hidden paths of Phantom Forest, which  are now open to you.",
    "name": "Map of Phantom Forest",
  },
  "3992041": {
    "desc": "A magical stone that unlocks the gates to the Inner Sanctum of Crimsonwood Keep. ",
    "name": "Crimsonwood Keystone",
  },
  "3993000": {
    "desc": "A pair of luck dish out of bamboos. Common in Korean culture",
    "name": "Lucky Dish",
  },
  "3993001": {
    "desc": "A red luck sack common in Korean culture.",
    "name": "Luck Sack",
  },
  "3993002": {
    "desc": "A pair of luck sack made of bamboo.",
    "name": "Bamboo Luck Sack",
  },
  "3993003": {
    "desc": "A red luck sack with 'luck' written on it.",
    "name": "Red Luck Sack",
  },
  "3994000": {
    "desc": "An alphabet \"A\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"A\"",
  },
  "3994001": {
    "desc": "An alphabet \"E\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"E\"",
  },
  "3994002": {
    "desc": "An alphabet \"I\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"I\"",
  },
  "3994003": {
    "desc": "An alphabet \"L\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"L\"",
  },
  "3994004": {
    "desc": "An alphabet \"N\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"N\"",
  },
  "3994005": {
    "desc": "An alphabet \"O\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"O\"",
  },
  "3994006": {
    "desc": "An alphabet \"P\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"P\"",
  },
  "3994007": {
    "desc": "An alphabet \"R\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"R\"",
  },
  "3994008": {
    "desc": "An alphabet \"T\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"T\"",
  },
  "3994009": {
    "desc": "An alphabet \"X\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"X\"",
  },
  "3994010": {
    "desc": "An alphabet \"Y\" made out of pasta. Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Alphabet Soup Pasta \"Y\"",
  },
  "3994011": {
    "desc": "An alphabet \"Z\" made out of pasta. Gather up other alphabets, and bring them all to the GM to...",
    "name": "Alphabet Soup Pasta \"Z\"",
  },
  "3994012": {
    "desc": "A special alphabet \"M\". Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Special \"M\"",
  },
  "3994013": {
    "desc": "A special alphabet \"S\". Gather up other alphabets, and bring them all to the Maple Administrator.",
    "name": "Special \"S\"",
  },
  "3994014": {
    "desc": "A special alphabet \"W\". Gather up other alphabets, and bring them all to the GM to...",
    "name": "Special \"W\"",
  },
  "3994015": { "name": "Wooden Alphabet C" },
  "3994016": { "name": "Wooden Alphabet H" },
  "3994017": {
    "desc": "An alphabet A. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet A",
  },
  "3994018": {
    "desc": "An alphabet E. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet E",
  },
  "3994019": {
    "desc": "An alphabet H. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet H",
  },
  "3994020": {
    "desc": "An alphabet N. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet N",
  },
  "3994021": {
    "desc": "An alphabet P. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet P",
  },
  "3994022": {
    "desc": "An alphabet R. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet R",
  },
  "3994023": {
    "desc": "An alphabet W. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet W",
  },
  "3994024": {
    "desc": "An alphabet Y. Collect other alphabets and hand them to Maple Administrator to...",
    "name": "Alphabet Y",
  },
  "3994085": {
    "desc": "A small candle from the Admin. This candle will turn itself off when the game is ended.",
    "name": "Admin's Candle",
  },
  "3994086": {
    "desc": "A candle used on the birthday cake for the 4th anniversary of Maplestory. The flame will be blown out when the player exits the game and lit again upon returning to the game.",
    "name": "Birthday Cake Candle",
  },
  "3994089": {
    "desc": "A memory chip Agent W left with me.  Information regarding 'Master M' is said to be contained in it.  If I don't enter the secret code every hour, it will self-destruct.",
    "name": "Agent W's Memory Chip",
  },
  "3994090": {
    "desc": "Mr. Oh sells these rare spices at the Maple 7th Day Market. You can sell them to Abdula for a profit. ",
    "name": "Spices",
  },
  "3994091": {
    "desc": "You can find these memorabilia from Thailand at the Maple 7th Day Market. You can sell them to Abdula for a profit. ",
    "name": "Memorabilia from Thailand",
  },
  "3994092": {
    "desc": "Lena sells delicious unagi at the Maple  7th Day Market. You can sell it to Abdula for a profit. ",
    "name": "Unagi",
  },
  "3994093": {
    "desc": "This taxydermy shark, handmade by Tae Gong himself, can be found at the Maple 7th Day Market. You can sell it to Abdula for a profit. ",
    "name": "Taxidermy Shark",
  },
  "3994094": {
    "desc": "Hanako sells this exquisite at the Maple 7th Day Market. You can sell it to Abdula for a profit. ",
    "name": "Crow-feather Hat",
  },
  "3994096": { "desc": "숫자1이다.", "name": "숫자1" },
  "3994097": { "desc": "숫자2이다.", "name": "숫자2" },
  "3994098": { "desc": "숫자3이다.", "name": "숫자3" },
  "3994099": { "desc": "숫자4이다.", "name": "숫자4" },
  "3994100": { "desc": "숫자5이다.", "name": "숫자5" },
  "3994101": {
    "desc": "A Giant Star that Cassandra made for you. If you hold it during the Starlight Festival, you can receive 1 Star Stamp every hour. \\n#cDisappears when you log out of the game.",
    "name": "Cassandra's Giant Star  ",
  },
  "3994102": {
    "desc": "A Letter N that looks like it would fit perfectly on the Empty Compass.",
    "name": "Letter N for Compass",
  },
  "3994103": {
    "desc": "A Letter E that looks like it would fit perfectly on the Empty Compass.",
    "name": "Letter E for Compass  ",
  },
  "3994104": {
    "desc": "A Letter W that looks like it would fit perfectly on the Empty Compass.",
    "name": "Letter W for Compass ",
  },
  "3994105": {
    "desc": "A Letter S that looks like it would fit perfectly on the Empty Compass.",
    "name": "Letter S for Compass ",
  },
  "3994106": {
    "desc": "A Maple Leaf that signifies Maple Story's 6 year journey. Something good will happen if you hold onto it for 1 hour.",
    "name": "6th Anniversary Maple Leaf of Journey ",
  },
  "3994115": { "desc": "Easy Mode", "name": "Easy Mode " },
  "3994116": { "desc": "Normal Mode ", "name": "Normal Mode " },
  "3994117": { "desc": "Hard Mode", "name": "Hard Mode" },
  "3994118": { "desc": "Hell Mode ", "name": "Hell Mode  " },
  "3994120": {
    "desc": "An unknown being that has yet to be explained.",
    "name": "Unknown",
  },
  "3994121": { "desc": "An Agent. ", "name": "Agent M" },
  "3994122": { "desc": "An Agent. ", "name": "Agent C" },
  "3994123": { "desc": "An Agent. ", "name": "Agent E" },
  "3994124": { "desc": "An Agent. ", "name": "Agent S" },
  "3994125": { "desc": "An Agent. ", "name": "Agent O" },
  "3994126": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994127": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994128": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994129": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994130": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994131": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994132": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994133": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994134": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994135": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994136": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994137": {
    "desc": "The Arans are reviving.",
    "name": "Aran Memory Fragments",
  },
  "3994138": {
    "desc": "A solid ice crystal that contains Maha Charm. Hold onto it for one hour and the crystal will melt, enabling you to acquire the Charm.",
    "name": "Ice Crystal",
  },
  "3994139": {
    "desc": "A charm that contains protection from Maha, the spirit of Polearm. Take this to Cassandra for a chance to answer questions and receive prizes.",
    "name": "Maha Charm",
  },
  "3994141": {
    "desc": "A small candle given by Cassandra. This candle will turn off automatically when the game ends.",
    "name": "Cassandra's Candle",
  },
  "3995000": { "name": "." },
}
