///|
typealias KeyCode = String

///|
pub let escape : KeyCode = "Escape"

///|
pub let digit1 = "Digit1"

///|
pub let digit2 = "Digit2"

///|
pub let digit3 = "Digit3"

///|
pub let digit4 = "Digit4"

///|
pub let digit5 = "Digit5"

///|
pub let digit6 = "Digit6"

///|
pub let digit7 = "Digit7"

///|
pub let digit8 = "Digit8"

///|
pub let digit9 = "Digit9"

///|
pub let digit0 = "Digit0"

///|
pub let minus = "Minus"

///|
pub let equal = "Equal"

///|
pub let backspace = "Backspace"

///|
pub let tab = "Tab"

///|
pub let keyQ = "KeyQ"

///|
pub let keyW = "KeyW"

///|
pub let keyE = "KeyE"

///|
pub let keyR = "KeyR"

///|
pub let keyT = "KeyT"

///|
pub let keyY = "KeyY"

///|
pub let keyU = "KeyU"

///|
pub let keyI = "KeyI"

///|
pub let keyO = "KeyO"

///|
pub let keyP = "KeyP"

///|
pub let bracketLeft = "BracketLeft"

///|
pub let bracketRight = "BracketRight"

///|
pub let enter = "Enter"

///|
pub let controlLeft = "ControlLeft"

///|
pub let keyA = "KeyA"

///|
pub let keyS = "KeyS"

///|
pub let keyD = "KeyD"

///|
pub let keyF = "KeyF"

///|
pub let keyG = "KeyG"

///|
pub let keyH = "KeyH"

///|
pub let keyJ = "KeyJ"

///|
pub let keyK = "KeyK"

///|
pub let keyL = "KeyL"

///|
pub let semicolon = "Semicolon"

///|
pub let quote = "Quote"

///|
pub let backquote = "Backquote"

///|
pub let shiftLeft = "ShiftLeft"

///|
pub let backslash = "Backslash"

///|
pub let keyZ = "KeyZ"

///|
pub let keyX = "KeyX"

///|
pub let keyC = "KeyC"

///|
pub let keyV = "KeyV"

///|
pub let keyB = "KeyB"

///|
pub let keyN = "KeyN"

///|
pub let keyM = "KeyM"

///|
pub let comma = "Comma"

///|
pub let period = "Period"

///|
pub let slash = "Slash"

///|
pub let shiftRight = "ShiftRight"

///|
pub let numpadMultiply = "NumpadMultiply"

///|
pub let altLeft = "AltLeft"

///|
pub let space = "Space"

///|
pub let capsLock = "CapsLock"

///|
pub let f1 = "F1"

///|
pub let f2 = "F2"

///|
pub let f3 = "F3"

///|
pub let f4 = "F4"

///|
pub let f5 = "F5"

///|
pub let f6 = "F6"

///|
pub let f7 = "F7"

///|
pub let f8 = "F8"

///|
pub let f9 = "F9"

///|
pub let f10 = "F10"

///|
pub let scrollLock = "ScrollLock"

///|
pub let numpad7 = "Numpad7"

///|
pub let numpad8 = "Numpad8"

///|
pub let numpad9 = "Numpad9"

///|
pub let numpadSubtract = "NumpadSubtract"

///|
pub let numpad4 = "Numpad4"

///|
pub let numpad5 = "Numpad5"

///|
pub let numpad6 = "Numpad6"

///|
pub let numpadAdd = "NumpadAdd"

///|
pub let numpad1 = "Numpad1"

///|
pub let numpad2 = "Numpad2"

///|
pub let numpad3 = "Numpad3"

///|
pub let numpad0 = "Numpad0"

///|
pub let numpadDecimal = "NumpadDecimal"

///|
pub let intlBackslash = "IntlBackslash"

///|
pub let f11 = "F11"

///|
pub let f12 = "F12"

///|
pub let numpadEqual = "NumpadEqual"

///|
pub let f13 = "F13"

///|
pub let f14 = "F14"

///|
pub let f15 = "F15"

///|
pub let f16 = "F16"

///|
pub let f17 = "F17"

///|
pub let f18 = "F18"

///|
pub let f19 = "F19"

///|
pub let f20 = "F20"

///|
pub let f21 = "F21"

///|
pub let f22 = "F22"

///|
pub let f23 = "F23"

///|
pub let kanaMode = "KanaMode"

///|
pub let lang2 = "Lang2"

///|
pub let lang1 = "Lang1"

///|
pub let intlRo = "IntlRo"

///|
pub let f24 = "F24"

///|
pub let lang4 = "Lang4"

///|
pub let lang3 = "Lang3"

///|
pub let convert = "Convert"

///|
pub let nonConvert = "NonConvert"

///|
pub let intlYen = "IntlYen"

///|
pub let numpadComma = "NumpadComma"

///|
pub let undo = "Undo"

///|
pub let paste = "Paste"

///|
pub let mediaTrackPrevious = "MediaTrackPrevious"

///|
pub let cut = "Cut"

///|
pub let copy = "Copy"

///|
pub let mediaTrackNext = "MediaTrackNext"

///|
pub let numpadEnter = "NumpadEnter"

///|
pub let controlRight = "ControlRight"

///|
pub let audioVolumeMute = "AudioVolumeMute"

///|
pub let launchApp2 = "LaunchApp2"

///|
pub let mediaPlayPause = "MediaPlayPause"

///|
pub let mediaStop = "MediaStop"

///|
pub let eject = "Eject"

///|
pub let audioVolumeDown = "AudioVolumeDown"

///|
pub let audioVolumeUp = "AudioVolumeUp"

///|
pub let browserHome = "BrowserHome"

///|
pub let numpadDivide = "NumpadDivide"

///|
pub let printScreen = "PrintScreen"

///|
pub let altRight = "AltRight"

///|
pub let help = "Help"

///|
pub let numLock = "NumLock"

///|
pub let pause = "Pause"

///|
pub let home = "Home"

///|
pub let arrowUp = "ArrowUp"

///|
pub let pageUp = "PageUp"

///|
pub let arrowLeft = "ArrowLeft"

///|
pub let arrowRight = "ArrowRight"

///|
pub let end = "End"

///|
pub let arrowDown = "ArrowDown"

///|
pub let pageDown = "PageDown"

///|
pub let insert = "Insert"

///|
pub let delete = "Delete"

///|
pub let metaLeft = "MetaLeft"

///|
pub let metaRight = "MetaRight"

///|
pub let contextMenu = "ContextMenu"

///|
pub let power = "Power"

///|
pub let sleep = "Sleep"

///|
pub let wakeUp = "WakeUp"

///|
pub let browserSearch = "BrowserSearch"

///|
pub let browserFavorites = "BrowserFavorites"

///|
pub let browserRefresh = "BrowserRefresh"

///|
pub let browserStop = "BrowserStop"

///|
pub let browserForward = "BrowserForward"

///|
pub let browserBack = "BrowserBack"

///|
pub let launchApp1 = "LaunchApp1"

///|
pub let launchMail = "LaunchMail"

///|
pub let mediaSelect = "MediaSelect"
